spring:
  application:
    name: pokemon-service
  datasource:
    url: jdbc:postgresql://localhost:5432/berijalanbootcamp
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cache:
    redis:
      time-to-live: 60000
    type: redis
    host: localhost
    port: 6379
    isCredential: false
    prefix: training_batch17
    default-ttl: 60

kafka:
  bootstrap-servers: localhost:9092

server:
  port: 8082
  servlet:
    context-path: /pokemon-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/